"""Add reviewer_notes to Receipt model

Revision ID: 1ac22301a0f8
Revises: dfe7c5c7f650
Create Date: 2025-03-31 12:08:47.574241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac22301a0f8'
down_revision = 'dfe7c5c7f650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('reviewer_notes')

    # ### end Alembic commands ###
