"""add archived column to receipts

Revision ID: cefff7ea281a
Revises: 4b6b252aa9d1
Create Date: 2024-01-xx xx:xx:xx.xxxx

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cefff7ea281a'
down_revision = '4b6b252aa9d1'
branch_labels = None
depends_on = None

def upgrade():
    # 1. Add column as nullable
    op.add_column('receipt', 
        sa.Column('archived', sa.Boolean(), nullable=True)
    )
    
    # 2. Update existing rows
    op.execute("UPDATE receipt SET archived = false")
    
    # 3. Set column to not nullable
    op.alter_column('receipt', 'archived',
        existing_type=sa.Boolean(),
        nullable=False,
        server_default='false'
    )

def downgrade():
    # Remove the archived column
    op.drop_column('receipt', 'archived')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
