"""Add reviewer role

Revision ID: dfe7c5c7f650
Revises: a1c2e90001d8
Create Date: 2025-02-11 14:02:26.390620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe7c5c7f650'
down_revision = 'a1c2e90001d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reviewer', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_reviewer')

    # ### end Alembic commands ###
